# Generated by Django 4.2.7 on 2023-12-12 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookblog', '0002_alter_blog_author_bookblogusers_blog_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='users',
        ),
        migrations.AddField(
            model_name='blog',
            name='contributors',
            field=models.ManyToManyField(related_name='contributions', through='bookblog.BookblogUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
