# Generated by Django 4.2.7 on 2023-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0003_remove_blog_starred_remove_blog_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='review',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
